#! /bin/bash

LocalDirectoryExtensions="$HOME/.local/share/gnome-shell/extensions"
LocalDirectoryBackgrounds="$HOME/.local/share/backgrounds"
LocalDirectoryThemes="$HOME/.local/share/themes"
LocalDirectoryCursors="$HOME/.local/share/icons"
LocalDirectoryIcons="$HOME/.local/share/icons"
LocalDirectoryFonts="$HOME/.local/share/fonts"

RootDirectoryExtensions="/usr/share/gnome-shell/extensions"
RootDirectoryBackgrounds="/usr/share/share/backgrounds"
RootDirectoryThemes="/usr/share/share/themes"
RootDirectoryCursors="/usr/share/share/icons"
RootDirectoryIcons="/usr/share/share/icons"
RootDirectoryFonts="/usr/share/share/fonts"

# Local
sudo rm --recursive --force "$LocalDirectoryExtensions"
echo "Clear $LocalDirectoryExtensions: Success."
sudo rm --recursive --force "$LocalDirectoryBackgrounds"
echo "Clear $LocalDirectoryBackgrounds: Success."
sudo rm --recursive --force "$LocalDirectoryThemes"
echo "Clear $LocalDirectoryThemes: Success."
sudo rm --recursive --force "$LocalDirectoryCursors"
echo "Clear $LocalDirectoryCursors: Success."
sudo rm --recursive --force "$LocalDirectoryIcons"
echo "Clear $LocalDirectoryIcons: Success."
sudo rm --recursive --force "$LocalDirectoryFonts"
echo "Clear $LocalDirectoryFonts: Success."

# Root
sudo rm --recursive --force "$RootDirectoryExtensions"
echo "Clear $RootDirectoryExtensions: Success."
sudo rm --recursive --force "$RootDirectoryBackgrounds"
echo "Clear $RootDirectoryBackgrounds: Success."
sudo rm --recursive --force "$RootDirectoryThemes"
echo "Clear $RootDirectoryThemes: Success."
sudo rm --recursive --force "$RootDirectoryCursors"
echo "Clear $RootDirectoryCursors: Success."
sudo rm --recursive --force "$RootDirectoryIcons"
echo "Clear $RootDirectoryIcons: Success."
sudo rm --recursive --force "$RootDirectoryFonts"
echo "Clear $RootDirectoryFonts: Success."

mkdir "$LocalDirectoryExtensions"
mkdir "$LocalDirectoryCursors"
mkdir "$LocalDirectoryThemes"
mkdir "$LocalDirectoryIcons"
mkdir "$LocalDirectoryFonts"
